import Head from 'next/head'
import { useState } from 'react';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Login from '@/components/login/login'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [authenticated, setAuthenticated] = useState<boolean>(true)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Login />
      </main>
    </>
  )
}
